### ISSUE TITLE
Ideation - Reflections, Brainstormed Ideas and Assumptions 

### ISSUE THREAD

**Issue by vkumar12180** [vkumar12180/ISDM-Group-2#10]
Should be 200-300 words. 
We will use our design thinking process - empathy maps and POV statements to base this. 
Put down your thoughts below.

**Comment by sassaf01** [comment]
Reflection has been completed in the AssignmentScaffold.md file. 

Brainstormed ideas are in the Lucidchart with the other files - the link can be found in the Brainstorm.md file.

Assumptions can be found in the AssignmentScaffold.md file.
