### ISSUE TITLE
Convert backlog into user stories. 

### ISSUE THREAD

**Issue by vkumar12180** [vkumar12180/ISDM-Group-2#18]

**Comment by vkumar12180** [comment]
should have about 12-15 user stories

**Comment by vkumar12180** [comment]
added 3 user stories in perspective or RM

**Comment by sassaf01** [comment]
Added 4 user stories for Travel Company and 3 for Developers

**Comment by ckesoglou** [comment]
Added user stories for Customers & System admin in #41 & #42

**Comment by Daniel832001** [comment]
Added 4 user stories for Airline companies
