### ISSUE TITLE
List of Stakeholders 

### ISSUE THREAD

**Issue by vkumar12180** [vkumar12180/ISDM-Group-2#4]
Write down a list of stakeholders in the comments for the assignment.

**Comment by sassaf01** [comment]
Are we sure we have covered all the major stakeholders?

**Comment by vkumar12180** [comment]
So far we came up with 
- Travel Company 
- Developers 
- Airports 
- RMs
- Customers 
- System Admin 
- Aviation Companies 
- Cruise Companies.

I believe this covers most of our stakeholders, but I guess we can check with our tutor, Moh to see what he thinks or whether we missed anything.

**Comment by vkumar12180** [comment]
merge airlines and airports. 
customer and RM is a primary ones. 
make an assumption on aviation and cruise being the same or not much different. 
developers and system admin are considered seperate. 
As discussed with mo, this is enough stakeholders.

**Comment by sassaf01** [comment]
DONE:
- Assumption on aviation/cruise being the same or not much different is completed 
- Assumption on developers and system admin being considered separate 

TO BE COMPLETED:
- merge airlines and airports, issues relating the empathy charts have been resolved but a new issue has been created to embody this so this will be closed.
