### ISSUE TITLE
Collaboration - Multiple changes / feedback

### ISSUE THREAD

**Issue by ckesoglou** [vkumar12180/ISDM-Group-2#56]
Relationship between object oriented classes and what is passed between them. Only for one Action / Use Case.

Very similar to the sequence diagram from BRM, although we don't need time, but we do need numbering.

Change the method names to be consistent with calling public methods from another class.

**Comment by ckesoglou** [comment]
eg: "updateCustomerProfile()" suggests that's a public method in Skills

**Comment by ckesoglou** [comment]
Refactored into two collaboration diagrams, one for inbound and one for outbound calls. This is more consistent with the activity diagrams. @sassaf01 could you please review and share any thoughts?

**Comment by sassaf01** [comment]
I think those diagrams look great! Don't forget to update them in the assignmentScaffold.md file and the diagrams folder! @ckesoglou

**Comment by ckesoglou** [comment]
Added new diagrams in e319c05

Fixed assignment scaffold with 665676b

Issue should be okay to close :)
